explaination:
  method: lime

input:
  class_names: ["0", "1"]
  input_type: np.array
  feature_names: ["X", "Y"]
  function: predict_proba
  values: [1.0, 1.0]

model:
  module: sklearn
  model_obj: svm.SVC
  weights: checkpoints/svm/xor_svm_model.pkl

output:
  name: xor_svm_explain
  path: results